source "https://rubygems.org"

gem "jekyll"
gem "minima", "~> 2.0"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  gem "kramdown"
  gem "kramdown-parser-gfm"
  gem "rouge"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.0", :install_if => Gem.win_platform?
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
gem 'public_suffix', '6.0.1'
